import './globals.css'
import { Montserrat, Josefin_Sans } from 'next/font/google'
import "bootstrap/dist/css/bootstrap.min.css";
import NavigationWrapper from './components/NavigationWrapper';
import FooterWrapper from './components/FooterWrapper';
import Providers from './redux/provider';

const montserrat = Montserrat({ subsets: ["latin"], display: 'swap', variable: "--montserrat" });
const josefin = Josefin_Sans({ subsets: ["latin"], display: "swap", variable: "--josefin" });

export const metadata = {
  title: 'Energialy - El Marketplace de Licitaciones de Oil & Gas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${montserrat.className} bg-[#F7F7F7] flex flex-col min-h-screen`}>
          <NavigationWrapper />
          {children}
          <FooterWrapper />
        </body>
      </Providers>
    </html>
  );
}
